### ISSUE TITLE
Finalize schedule

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-may-training#6]
We might update the schedule to include specific timing once we have a dry run under our belts.

**Comment by jaclyn-taroni** [comment]
Discussed via Slack, but don't think this is documented anywhere else yet - the [cheatsheets directory](https://github.com/AlexsLemonade/training-modules/tree/master/module-cheatsheets) should be linked in the schedule for consultation days and module-specific cheatsheets should be linked in the schedule for instruction days (e.g., intro to R on Monday).

**Comment by cbethell** [comment]
I will work on this today. Are there any other additional changes that may be beneficial to add to the schedule at this time?

Also, have we decided on specific time slots based on our dry run?

**Comment by jashapiro** [comment]
If we want to specify tentative times on the schedule, I would suggest 30 min welcome/intro. Then 1 hr for each workbook. That gives 30 min of slack...

For the links, I would suggest we should link to the module ReadMe at the start of each day? 

I might then leave the completed workbooks as the individual links, as those are nicely rendered, while the `-live` markdown file is not. I go back and forth on that one though.

**Comment by cbethell** [comment]
> If we want to specify tentative times on the schedule, I would suggest 30 min welcome/intro. Then 1 hr for each workbook. That gives 30 min of slack...

@jashapiro, with this timing, there would be no room for breaks, is that what we would want? For example:

| Time        | Topic                                          |
|-------------|--------------------------------------|
| **Day 1**   | **Monday, 2020-05-04**                         |
| 12:00 PM    | Welcome, Introductions and Getting Started |
|  12:30 PM           | [Introduction to R](https://alexslemonade.github.io/training-modules/intro-to-R-tidyverse/01-intro_to_base_R.nb.html)                                |
|  1:30 PM           | [R Introduction to ggplot](https://alexslemonade.github.io/training-modules/intro-to-R-tidyverse/02-intro_to_ggplot2.nb.html)      |
|  2:30 PM           | [R Introduction to tidyverse](https://alexslemonade.github.io/training-modules/intro-to-R-tidyverse/03-intro_to_tidyverse.nb.html)      |
|  3:30 PM           | Exercises Introduction: [Intro to R](https://github.com/AlexsLemonade/training-modules/blob/master/intro-to-R-tidyverse/04a-intro_to_R_exercise.Rmd)|
| 4:00        | End             |
> For the links, I would suggest we should link to the module ReadMe at the start of each day?
 
Will do.

> I might then leave the completed workbooks as the individual links, as those are nicely rendered, while the `-live` markdown file is not. I go back and forth on that one though.

I do like that the completed workbooks are nicely rendered.

**Comment by jashapiro** [comment]
If we want to specify breaks, I would probably do 45 minutes on, 15 min break for each notebook? That is what I was planning to aim for. So add in 15 min breaks at 1:15 and 2:15? We will go right into the Exercises Intro at the end, as people can take whatever breaks they want on their own after that.

**Comment by cbethell** [comment]
> If we want to specify breaks, I would probably do 45 minutes on, 15 min break for each notebook? That is what I was planning to aim for. So add in 15 min breaks at 1:15 and 2:15? We will go right into the Exercises Intro at the end, as people can take whatever breaks they want on their own after that.

Sounds good to me! Thank you!

**Comment by jaclyn-taroni** [comment]
> If we want to specify tentative times on the schedule, I would suggest 30 min welcome/intro. Then 1 hr for each workbook. That gives 30 min of slack...

I would say for _bulk RNA-seq_ I would put 45 min each for the 5 notebooks or markdown docs we need to cover and a 15 min break between 03 and 04. I think this is likely to be somewhat inaccurate and some of them will be shorter than that.

**Comment by cbethell** [comment]
I updated the [schedule on training Wiki](https://github.com/AlexsLemonade/2020-may-training/wiki/Schedule) to reflect what we discussed above @jaclyn-taroni and @jashapiro.

Let me know if I missed anything or if I should change anything.

**Comment by jaclyn-taroni** [comment]
The URL needs to end with `#zoom-on-consultation-days` because the header got updated in a recent pull request. I'll make the switch now.

**Comment by jaclyn-taroni** [comment]
Any remaining changes are covered by #8
