### ISSUE TITLE
Update Wiki to use permalinks

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-may-training#8]
Currently only some links in the Wiki pages use permalinks (typically those pertaining to training notebooks). We should standardize this around end of day on Friday. 

To get a permalink version of rendered notebooks for the **Schedule** we can use [htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) - here's an example of the current version of the first intro to R notebook: https://htmlpreview.github.io/?https://github.com/AlexsLemonade/training-modules/blob/5006220740dde7b252f98458f6a0ad7fad09be5b/intro-to-R-tidyverse/01-intro_to_base_R.nb.html

You can navigate to https://htmlpreview.github.io and then paste the permalink version of the URL into the box and it will put together the URL to the preview for you.

- [x] Home
- [x] Resources for Consultation Days
- [x] Schedule
- [x] Software Setup
- [x] Workshop Materials
- [x] Workshop Structure

**Comment by jashapiro** [comment]
While [htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) works and performs a reasonable job, I don't love that it is not a native solution, i.e. that we are relying on a 3rd party that could result in broken links if it goes away.

**Comment by jaclyn-taroni** [comment]
Both solutions (use GitHub pages serving from master, htmlpreview with permalink) are dissatisfying in some way for sure. Unless we can find a better alternative that let’s us link to specific versions, let’s try the htmlpreview route for this training workshop so we can be consistent about tying the materials to a specific commit.

**Comment by jaclyn-taroni** [comment]
Done!
